-- ---------------------------------------------------------------------------
-- Cronsole: central scheduled-job service
--
-- Authoritative schema. There are no migration files in this repository: this
-- file is the definition, and a transition from an older revision is handed
-- over as an explicit script (upgrade.sql) to run once.
--
-- PostgreSQL 15+.
--
-- The model in one paragraph. A project registers jobs. A job carries the
-- request to fire and one or more cron expressions. Every minute the
-- dispatcher turns the expressions that are due into job_runs rows, and the
-- runner claims those rows one at a time. A run row is therefore the unit of
-- history: it records who asked for it, when it started, how long it took,
-- what came back and what failed. Nothing executes without leaving one.
-- ---------------------------------------------------------------------------

BEGIN;

-- ---------------------------------------------------------------------------
-- users
--
-- Accounts are created by an admin; there is no public sign up.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname           text        NOT NULL,
    email              text        NOT NULL,
    password           text        NOT NULL,
    phone              text        NOT NULL DEFAULT '',
    is_admin           boolean     NOT NULL DEFAULT false,
    active             boolean     NOT NULL DEFAULT true,
    last_login         timestamptz,
    tokens_valid_after timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz,
    deleted_at         timestamptz
);

COMMENT ON COLUMN users.tokens_valid_after IS 'tokens issued before this moment are rejected; set on logout and password change.';

-- Serves the login lookup, and is the uniqueness rule itself. Partial so a
-- soft-deleted account does not reserve its address forever.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (lower(email)) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- password_resets
--
-- One row per "I forgot my password" request.
--
-- The token is stored HASHED. A reset link is a bearer credential for the
-- account it belongs to, so a leak of this table would otherwise be a leak of
-- every account in it; the raw value exists only in the message that was sent.
-- Single use through used_at and short lived through expires_at, because the
-- window in which a link works is the window in which a forwarded or logged
-- mail is worth stealing.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS password_resets (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash text        NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN password_resets.token_hash IS 'sha256 of the token that was mailed. The raw token is never stored.';
COMMENT ON COLUMN password_resets.used_at IS 'set the moment the token is spent, so a link cannot be replayed.';

-- The lookup is by hash, and the uniqueness is the guard: the same token can
-- never be live twice.
CREATE UNIQUE INDEX IF NOT EXISTS password_resets_token_key ON password_resets (token_hash);
-- Indexes the foreign key, and serves "retire the account's other outstanding
-- links" when one of them is used.
CREATE INDEX IF NOT EXISTS password_resets_user_idx ON password_resets (user_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- projects
--
-- One row per system that owns scheduled work. It is the unit of ownership,
-- of API access, and of containment.
--
-- base_url is the containment mechanism, not a convenience. When it is set,
-- every job under the project must give a relative target and the host comes
-- from this column, so an account that can edit jobs still cannot point one at
-- an arbitrary address. Projects that genuinely need to call several hosts
-- leave it empty and accept absolute targets.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text        NOT NULL,
    slug           text        NOT NULL,
    description    text        NOT NULL DEFAULT '',
    base_url       text        NOT NULL DEFAULT '',
    api_key_prefix text        NOT NULL DEFAULT '',
    api_key_hash   text        NOT NULL DEFAULT '',
    active         boolean     NOT NULL DEFAULT true,
    user_id        bigint      REFERENCES users (id) ON DELETE SET NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz,
    deleted_at     timestamptz
);

COMMENT ON COLUMN projects.slug IS 'stable machine name used by the sync API; lower case, digits, dash.';
COMMENT ON COLUMN projects.base_url IS 'when set, job targets must be relative and are resolved against it.';
COMMENT ON COLUMN projects.api_key_prefix IS 'first characters of the API key, stored so a key can be identified without holding it.';
COMMENT ON COLUMN projects.api_key_hash IS 'sha256 of the API key. The key itself is shown once, at creation, and never stored.';

CREATE UNIQUE INDEX IF NOT EXISTS projects_slug_key ON projects (slug) WHERE deleted_at IS NULL;
-- API authentication looks the project up by key prefix before comparing hashes.
CREATE INDEX IF NOT EXISTS projects_api_key_prefix_idx ON projects (api_key_prefix) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS projects_user_id_idx ON projects (user_id);

-- ---------------------------------------------------------------------------
-- notifications
--
-- A named recipient set plus the outcomes it wants to hear about. Attached to
-- a job, so several jobs can share one on-call list.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      REFERENCES users (id) ON DELETE SET NULL,
    name       text        NOT NULL,
    on_success boolean     NOT NULL DEFAULT false,
    on_failure boolean     NOT NULL DEFAULT true,
    active     boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz,
    deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS notifications_user_id_idx ON notifications (user_id);

CREATE TABLE IF NOT EXISTS notify_emails (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id bigint      NOT NULL REFERENCES notifications (id) ON DELETE CASCADE,
    email           text        NOT NULL,
    active          boolean     NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notify_emails_notification_id_idx ON notify_emails (notification_id);
CREATE UNIQUE INDEX IF NOT EXISTS notify_emails_unique ON notify_emails (notification_id, lower(email));

-- ---------------------------------------------------------------------------
-- jobs
--
-- One row is one scheduled job: what to call, how patiently, and how it
-- behaves when it overlaps itself or when the dispatcher was late.
--
-- A job carries no cron expression of its own. Expressions live in
-- job_schedules because a real job frequently needs several that cannot be
-- folded into one ("*/5 * * * *" plus "58,59 15 * * *").
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       bigint      NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    code             text        NOT NULL,
    name             text        NOT NULL,
    description      text        NOT NULL DEFAULT '',
    tag              text        NOT NULL DEFAULT '',

    method           text        NOT NULL DEFAULT 'GET'
                                 CHECK (method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD')),
    url              text        NOT NULL,
    body             text        NOT NULL DEFAULT '',

    timeout_sec      integer     NOT NULL DEFAULT 30  CHECK (timeout_sec BETWEEN 1 AND 600),
    max_duration_sec integer     NOT NULL DEFAULT 300 CHECK (max_duration_sec BETWEEN 1 AND 86400),
    retries          smallint    NOT NULL DEFAULT 0   CHECK (retries BETWEEN 0 AND 5),

    single_run       boolean     NOT NULL DEFAULT true,
    run_missed       boolean     NOT NULL DEFAULT false,
    max_delay_min    integer     NOT NULL DEFAULT 10  CHECK (max_delay_min BETWEEN 0 AND 1440),
    priority         integer     NOT NULL DEFAULT 100,

    success_min      integer     NOT NULL DEFAULT 200 CHECK (success_min BETWEEN 100 AND 599),
    success_max      integer     NOT NULL DEFAULT 399 CHECK (success_max BETWEEN 100 AND 599),

    notification_id  bigint      REFERENCES notifications (id) ON DELETE SET NULL,

    active           boolean     NOT NULL DEFAULT false,
    last_run_at      timestamptz,
    last_status      text,
    last_duration_ms integer,

    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz,
    deleted_at       timestamptz,

    CHECK (success_max >= success_min),
    CHECK (max_duration_sec >= timeout_sec)
);

COMMENT ON COLUMN jobs.code IS 'stable machine name, unique inside the project. History and chain links are keyed by it, so it is never renamed.';
COMMENT ON COLUMN jobs.url IS 'absolute address, or a path resolved against projects.base_url when that column is set.';
COMMENT ON COLUMN jobs.timeout_sec IS 'the client gives up after this. The target may well carry on running, so the run is recorded as timeout rather than failure.';
COMMENT ON COLUMN jobs.max_duration_sec IS 'a run still marked running after this is considered stuck and closed by the watchdog. Must exceed timeout_sec.';
COMMENT ON COLUMN jobs.single_run IS 'when true a new run is skipped while the previous one is still running.';
COMMENT ON COLUMN jobs.run_missed IS 'when true, minutes the dispatcher was down for are replayed, up to max_delay_min.';
COMMENT ON COLUMN jobs.priority IS 'lower goes first among jobs falling on the same minute.';
COMMENT ON COLUMN jobs.active IS 'a job is created inactive; it cannot be activated until it has at least one schedule.';

CREATE UNIQUE INDEX IF NOT EXISTS jobs_project_code_key ON jobs (project_id, lower(code)) WHERE deleted_at IS NULL;
-- The dispatcher's per-minute scan: every active job, in priority order.
CREATE INDEX IF NOT EXISTS jobs_active_priority_idx ON jobs (priority, id) WHERE active AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS jobs_project_id_idx ON jobs (project_id);
CREATE INDEX IF NOT EXISTS jobs_notification_id_idx ON jobs (notification_id);

-- ---------------------------------------------------------------------------
-- job_headers
--
-- Sent with the request. is_secret only hides the value in the interface; it
-- is not encryption, and the column says so rather than implying more.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_headers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     bigint      NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    key        text        NOT NULL,
    value      text        NOT NULL,
    is_secret  boolean     NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN job_headers.is_secret IS 'masks the value on screen and in API responses. Storage is plain text.';

CREATE INDEX IF NOT EXISTS job_headers_job_id_idx ON job_headers (job_id);
CREATE UNIQUE INDEX IF NOT EXISTS job_headers_unique ON job_headers (job_id, lower(key));

-- ---------------------------------------------------------------------------
-- job_schedules
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_schedules (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     bigint      NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    expression text        NOT NULL,
    active     boolean     NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN job_schedules.expression IS 'five field cron expression: minute hour day-of-month month day-of-week.';

-- The dispatcher loads every active expression once per minute, grouped by job.
CREATE INDEX IF NOT EXISTS job_schedules_job_active_idx ON job_schedules (job_id) WHERE active;
CREATE UNIQUE INDEX IF NOT EXISTS job_schedules_unique ON job_schedules (job_id, expression);

-- ---------------------------------------------------------------------------
-- job_links
--
-- Chain: when a job finishes, run another one without waiting for its clock.
--
-- A separate table rather than a column on jobs, because one job commonly
-- triggers several and the relationship changes over time.
--
-- delay_sec exists because the triggering job's writes may not be committed
-- the instant its HTTP response returns; a dependent job that starts too early
-- reads half the data.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_links (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id        bigint      NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    target_job_id bigint      NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    condition     text        NOT NULL DEFAULT 'success'
                              CHECK (condition IN ('success', 'failure', 'always')),
    delay_sec     integer     NOT NULL DEFAULT 15 CHECK (delay_sec BETWEEN 0 AND 3600),
    active        boolean     NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),

    CHECK (job_id <> target_job_id)
);

COMMENT ON COLUMN job_links.condition IS 'which outcome of the source job fires this link. timeout never counts as success: whether the target finished is unknown.';

CREATE UNIQUE INDEX IF NOT EXISTS job_links_unique ON job_links (job_id, target_job_id, condition);
-- Read at the end of every successful run, to find what to trigger next.
CREATE INDEX IF NOT EXISTS job_links_job_active_idx ON job_links (job_id) WHERE active;
CREATE INDEX IF NOT EXISTS job_links_target_job_id_idx ON job_links (target_job_id);

-- ---------------------------------------------------------------------------
-- job_runs
--
-- The execution record, and the queue at the same time. A row is created in
-- pending, claimed into running, and closed into one of the terminal states.
--
-- UNIQUE (job_id, planned_minute) is the safety catch of the whole system: two
-- dispatcher instances reaching the same minute cannot produce two runs.
-- planned_minute is NULL for manual, chained and API triggered runs, and
-- Postgres allows many NULLs, so pressing "run now" twice is still allowed.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_runs (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id         bigint      NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    planned_minute timestamptz,
    run_after      timestamptz,
    trigger        text        NOT NULL DEFAULT 'schedule'
                               CHECK (trigger IN ('schedule', 'manual', 'chain', 'api')),
    user_id        bigint      REFERENCES users (id) ON DELETE SET NULL,
    parent_run_id  bigint      REFERENCES job_runs (id) ON DELETE SET NULL,

    status         text        NOT NULL DEFAULT 'pending'
                               CHECK (status IN ('pending', 'running', 'success', 'failed', 'timeout', 'skipped')),
    attempt        smallint    NOT NULL DEFAULT 0,
    instance_id    text        NOT NULL DEFAULT '',

    started_at     timestamptz,
    finished_at    timestamptz,
    duration_ms    integer,
    http_status    integer,
    request_url    text        NOT NULL DEFAULT '',
    output         text        NOT NULL DEFAULT '',
    error          text        NOT NULL DEFAULT '',

    created_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN job_runs.planned_minute IS 'the minute this run belongs to, seconds zeroed. NULL when the run was not produced by a schedule.';
COMMENT ON COLUMN job_runs.run_after IS 'the run is not handed to the runner before this moment. Used by chain delays.';
COMMENT ON COLUMN job_runs.parent_run_id IS 'the run whose completion triggered this one. Answers "why did this run".';
COMMENT ON COLUMN job_runs.instance_id IS 'which process claimed the run, so a stuck run can be traced to a replica.';
COMMENT ON COLUMN job_runs.output IS 'response body, truncated. Diagnostics only, never the source of truth.';
COMMENT ON COLUMN job_runs.request_url IS 'the address actually called, recorded because base_url and params can change afterwards.';

CREATE UNIQUE INDEX IF NOT EXISTS job_runs_job_minute_key ON job_runs (job_id, planned_minute) WHERE planned_minute IS NOT NULL;
-- The dispatcher's hand-off query: pending rows whose run_after has arrived.
CREATE INDEX IF NOT EXISTS job_runs_pending_idx ON job_runs (run_after, id) WHERE status = 'pending';
-- Concurrency accounting, and the watchdog's stuck-run scan.
CREATE INDEX IF NOT EXISTS job_runs_running_idx ON job_runs (job_id, started_at) WHERE status = 'running';
-- The run list, per job and overall, newest first.
CREATE INDEX IF NOT EXISTS job_runs_job_created_idx ON job_runs (job_id, created_at DESC);
CREATE INDEX IF NOT EXISTS job_runs_created_idx ON job_runs (created_at DESC);
-- Dashboard counters over the last 24 hours, and retention pruning.
CREATE INDEX IF NOT EXISTS job_runs_status_created_idx ON job_runs (status, created_at DESC);
CREATE INDEX IF NOT EXISTS job_runs_parent_idx ON job_runs (parent_run_id);
CREATE INDEX IF NOT EXISTS job_runs_user_idx ON job_runs (user_id);

-- ---------------------------------------------------------------------------
-- heartbeat
--
-- The dispatcher's own pulse, one row. The watchdog reads it: if last_run is
-- stale the dispatcher is down, and nothing else in the system would say so.
--
-- drift_sec is the application clock minus the database clock. Both matter
-- because the minute is taken from the database while the tick is fired by the
-- application, and the two drifting apart is what makes a job fire in the
-- wrong minute.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS heartbeat (
    id          smallint    PRIMARY KEY CHECK (id = 1),
    last_run    timestamptz NOT NULL,
    app_time    timestamptz,
    drift_sec   integer     NOT NULL DEFAULT 0,
    instance_id text        NOT NULL DEFAULT '',
    note        text        NOT NULL DEFAULT ''
);

COMMENT ON COLUMN heartbeat.note IS 'watchdog repeat marker: a fingerprint of the last warning set that was mailed, so the same alarm is not resent every sweep.';

INSERT INTO heartbeat (id, last_run) VALUES (1, now()) ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- app_logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_logs (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level      text        NOT NULL,
    message    text        NOT NULL,
    detail     text        NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN app_logs.level IS 'info, warn, error.';

CREATE INDEX IF NOT EXISTS app_logs_created_idx ON app_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS app_logs_level_created_idx ON app_logs (level, created_at DESC);

-- ---------------------------------------------------------------------------
-- host_overrides
--
-- Where a hostname is actually dialled, without changing the job that names it.
--
-- The problem it solves: a job calls https://shop.example.com/cron/x, public
-- DNS points that name at a CDN, and the request leaves the VM and comes back
-- through it to reach a service on the same private network. An entry here
-- sends the connection straight to 10.10.0.5 while the Host header and the TLS
-- server name stay shop.example.com, so the certificate still validates and the
-- origin still routes by name. It is exactly what `curl --resolve` does.
--
-- Why a table rather than /etc/hosts: no root, no shell, the same behaviour in
-- a container and under Kubernetes without hostAliases, and it is visible,
-- auditable and in the backup.
--
-- SECURITY. An arbitrary hostname-to-address map is an SSRF primitive: it can
-- point a permitted host at any address and walk past the target policy's host
-- checks. So it is platform-administrator only, never delegated to a project
-- role, and global rather than per project, because a project administrator
-- redirecting their own host is the same attack with extra steps. The address
-- is an IP literal, never a name, so nothing here can trigger a second lookup.
--
-- port NULL means every port. A row naming a port wins over one that does not.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS host_overrides (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostname   text        NOT NULL CHECK (hostname <> '' AND length(hostname) <= 253),
    address    inet        NOT NULL,
    port       integer     CHECK (port IS NULL OR (port BETWEEN 1 AND 65535)),
    note       text        NOT NULL DEFAULT '',
    active     boolean     NOT NULL DEFAULT true,
    -- RESTRICT, not CASCADE: deleting the account that added a route must not
    -- silently change where traffic goes.
    created_by bigint      REFERENCES users (id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN host_overrides.port IS 'NULL means every port. A row naming a port takes precedence over one that does not.';
COMMENT ON COLUMN host_overrides.address IS 'An IP literal. A hostname here would mean a second DNS lookup, which is the thing this exists to avoid.';

-- One route per hostname and port. coalesce folds the "every port" row into the
-- same uniqueness rule, so it cannot be entered twice.
CREATE UNIQUE INDEX IF NOT EXISTS host_overrides_host_port_key
    ON host_overrides (lower(hostname), coalesce(port, 0));

-- Serves the dialer's reload: "every active route, by hostname".
CREATE INDEX IF NOT EXISTS host_overrides_active_idx ON host_overrides (lower(hostname)) WHERE active;

-- Serves the foreign key, so deleting an account does not scan this table.
CREATE INDEX IF NOT EXISTS host_overrides_created_by_idx ON host_overrides (created_by);

-- ---------------------------------------------------------------------------
-- Authorization: roles, permissions and who holds what.
--
-- These five tables belong to github.com/mstgnz/grantz and are copied verbatim
-- from its migrations/001_init_postgres.sql at v0.4.0. They are here rather than
-- referenced so that one file sets up the whole database; re-copy them when the
-- grantz dependency is upgraded and its schema changes.
--
-- What goes in them: the permission catalogue and the three built-in roles are
-- written from code at every boot, so upgrading the binary upgrades what a role
-- can do. Only the ROLE MAPPING, who holds which role over which projects, is
-- data an administrator edits, and the interface writes it.
--
-- grantz deliberately does not own users. grantz_user_roles.user_id is a plain
-- bigint in the module's own file; the foreign key below is ours, because our
-- users table can support it and an orphaned grant is a grant nobody can see to
-- revoke.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS grantz_permissions (
    key         varchar(150) PRIMARY KEY,
    resource    varchar(100) NOT NULL,
    action      varchar(50)  NOT NULL,
    description varchar(500),
    has_fields  boolean      NOT NULL DEFAULT false,
    created_at  timestamp    NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS grantz_permissions_resource_idx ON grantz_permissions (resource);

CREATE TABLE IF NOT EXISTS grantz_roles (
    id          serial PRIMARY KEY,
    key         varchar(100) NOT NULL UNIQUE,
    name        varchar(150) NOT NULL,
    description varchar(500),
    active      boolean      NOT NULL DEFAULT true,
    created_at  timestamp    NOT NULL DEFAULT now(),
    updated_at  timestamp
);

-- fields NULL means every field. A restriction is an allow-list on purpose:
-- with a deny-list, a column added later would leak automatically.
CREATE TABLE IF NOT EXISTS grantz_role_permissions (
    role_id        integer      NOT NULL REFERENCES grantz_roles (id) ON DELETE CASCADE,
    permission_key varchar(150) NOT NULL REFERENCES grantz_permissions (key) ON DELETE CASCADE,
    fields         jsonb,
    conditions     jsonb,
    created_at     timestamp    NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, permission_key)
);

-- The key is (user_id, role_id), so one assignment carries one scope. A role
-- held over two projects is ONE row naming both: {"project_ids": [1, 2]}. An
-- assignment with no scope reaches every project and hides any narrower scope
-- the same user holds for the same permission.
CREATE TABLE IF NOT EXISTS grantz_user_roles (
    user_id    bigint    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id    integer   NOT NULL REFERENCES grantz_roles (id) ON DELETE CASCADE,
    scope      jsonb,
    created_at timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS grantz_user_roles_user_idx ON grantz_user_roles (user_id);

-- The answer to role explosion: one person needing slightly more or less than
-- their role gets a row here instead of a cloned role. 'deny' always wins over
-- any grant, including one from a role.
CREATE TABLE IF NOT EXISTS grantz_user_permissions (
    user_id        bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    permission_key varchar(150) NOT NULL REFERENCES grantz_permissions (key) ON DELETE CASCADE,
    effect         varchar(10)  NOT NULL CHECK (effect IN ('allow', 'deny')),
    fields         jsonb,
    created_at     timestamp    NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, permission_key)
);

CREATE INDEX IF NOT EXISTS grantz_user_permissions_user_idx ON grantz_user_permissions (user_id);

COMMIT;
