apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cronsole-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - cronsole.example.com
      secretName: cronsole-tls
  rules:
    - host: cronsole.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cronsole-service
                port:
                  number: 80
